### ISSUE TITLE
 OSX. Don't work

### ISSUE THREAD

**Issue by gumeniukcom** [ewnd9/badtaste#2]
After start ( login ) - not play.

after two space-button click:

```
sgumenyuk:~ sgumenyuk$ badtaste
ReferenceError: playlist is not defined
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/badtaste/src/components/main.js:37:17)
    at EventEmitter.emit (events.js:104:17)
    at Screen.<anonymous> (/usr/local/lib/node_modules/badtaste/src/index.js:12:39)
    at Screen.EventEmitter._emit (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/events.js:94:20)
    at Screen.EventEmitter.emit (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/events.js:114:17)
    at Program.<anonymous> (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/widgets/screen.js:593:12)
    at Program.emit (events.js:110:17)
    at /usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/program.js:410:15
    at Array.forEach (native)
    at ReadStream.input.on.input._keypressHandler (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/program.js:408:23)
    at ReadStream.emit (events.js:110:17)
    at /usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/keys.js:318:14
    at Array.forEach (native)
    at emitKeys (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/keys.js:134:10)
    at ReadStream.onData (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/keys.js:49:14)
    at ReadStream.emit (events.js:129:20)
```

**Comment by ewnd9** [comment]
Badtaste uses [player](https://github.com/guo-yu/player) package under hood to play audio. You could try to install directly that package and look if it plays audio:

```
npm install -g player
player play ~/audio/track.mp3 # any local track
```

Also playlist error is fixed in `v0.0.6`

**Comment by shatteringlass** [comment]
This is the error for me on OSX 10.11.1  

``` bash
$ badtaste
/usr/local/lib/node_modules/badtaste/src/helpers/credentials.js:41
    return gmCredentials.init().then(function () {
                               ^

TypeError: Cannot read property 'then' of undefined
    at exports.default (/usr/local/lib/node_modules/badtaste/src/helpers/credentials.js:21:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/badtaste/src/index.js:18:1)
    at Module._compile (module.js:434:26)
    at normalLoader (/usr/local/lib/node_modules/badtaste/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/badtaste/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/badtaste/cli.js:21:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
```

**Comment by ewnd9** [comment]
@shatteringlass thanks for reply, I've just uploaded fix with `v0.2.2`

**Comment by shatteringlass** [comment]
Thank you, now VK plays ok. Google music search causes a segfault, at least I think: the program exits abruptly without any output right after pressing "enter" on the "search query" input box.

**Comment by ewnd9** [comment]
@shatteringlass most possible there is a problem with authentication, did you use one time password (https://security.google.com/settings/security/apppasswords)? If you install `v0.2.3` you can see actual error and stacktrace at `~/.badtaste-npm-info.log`

**Comment by shatteringlass** [comment]
thanks, updated. log says:  

```
Error: error getting search results: Error: 404 error from server
    at /usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:322:24
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:86:48)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickDomainCallback (node.js:384:17)
[../deps/mpg123/src/libmpg123/id3.c:345] error: No comment text / valid description?
```

**Comment by ewnd9** [comment]
@shatteringlass Hi, first of all, sorry for such the huge delay. I've discovered that 404 pops up when a user doesn't have all access on google music. I've introduced another method `GM All Tracks` in `v0.6.0` which is available for all users, please, try it
