### ISSUE TITLE
Crash on closing help

### ISSUE THREAD

**Issue by vkotovv** [ewnd9/badtaste#3]
After some manipulations with help got this crash:

```
ReferenceError: playlist is not defined
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/badtaste/src/components/main.js:37:17)
    at EventEmitter.emit (events.js:104:17)
    at Screen.<anonymous> (/usr/local/lib/node_modules/badtaste/src/index.js:12:39)
    at Screen.EventEmitter._emit (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/events.js:94:20)
    at Screen.EventEmitter.emit (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/events.js:114:17)
    at Program.<anonymous> (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/widgets/screen.js:593:12)
    at Program.emit (events.js:110:17)
    at /usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/program.js:410:15
    at Array.forEach (native)
    at ReadStream.input.on.input._keypressHandler (/usr/local/lib/node_modules/badtaste/node_modules/blessed/lib/program.js:408:23)
    at ReadStream.emit (events.js:110:17)
    at readline.js:1175:14
    at Array.forEach (native)
    at emitKeys (readline.js:993:10)
    at ReadStream.onData (readline.js:910:14)
    at ReadStream.emit (events.js:129:20)
```

I'm using Ubuntu 14.04.3, badtaste 0.0.4. What other details should I mention?

**Comment by vkotovv** [comment]
Got it 100% reproducible: start badtaste, hit "?" and then spacebar 2 times.

**Comment by ewnd9** [comment]
Fixed in `v0.0.5`

**Comment by vkotovv** [comment]
Another error now:

```
Error: EACCES, open '/usr/local/lib/node_modules/badtaste/logs/badtaste-info.log'
    at Error (native)
```

Maybe thats because I installed it via `sudo npm install -g badtaste`. Should I use sudo for installation or not?

**Comment by ewnd9** [comment]
I publish `v0.0.6` with logs in home folder, which fixes that problem

However,  you'd better setup npm to install global packages to home folder and always install without sudo:

```
npm config set prefix '~/.npm-packages'
export PATH="$PATH:$HOME/.npm-packages/bin" in your .bashrc/.zshrc
```
